#!/usr/bin/python
# -*- coding: utf-8 -*-

# PARAMETROS DE SPECTROGRAMA
NFFT = 2**11
HOP_LENGTH = 2**9
MAX_LENGTH = None
BIN_TIME = None
BIN_FREQ = None

# PARAMETROS DE ANOTACIONES DE ESPECTROGRAMA
FREQ_UNITS = 1000  # 1 equivale a 1000 hz
POINT_LIST_NAME = 'rverts'
ANOTATION_CLASS_NAME = 'species'

# CORTE DE LLAMADOS
TIME_PADDING = 0.01
TIME_WIDTH = None  # segundos
FREQ_HEIGHT = None  # Hz

# TASA DE MUESTREO ESTANDAR
SAMPLERATE = 16000

# DURACION DE CORTE DE AUDIO
MAX_DURATION = 2
